DROP TABLE IF EXISTS I_Airport_Passengers;
DROP TABLE IF EXISTS I_City_Populations;
DROP TABLE IF EXISTS I_Climate_Precipitation;
DROP TABLE IF EXISTS I_Climate_Low;
DROP TABLE IF EXISTS I_Climate_High;
DROP TABLE IF EXISTS I_Cost_Indexes;
DROP TABLE IF EXISTS I_Density;
