let AirportData = [
    {label:"Albuquerque International Sunport",value:"ABQ"},
    {label:"Merrill Field",value:"MRI"},
    {label:"Lake Hood Seaplane Base",value:"LHD"},
    {label:"Ted Stevens Anchorage International Airport",value:"ANC"},
    {label:"Hartsfield?Jackson Atlanta International Airport",value:"ATL"},
    {label:"Austin-Bergstrom International Airport",value:"AUS"},
    {label:"Meadows Field",value:"BFL"},
    {label:"Baton Rouge Metropolitan Airport",value:"BTR"},
    {label:"Gen. Edward Lawrence Logan International Airport",value:"BOS"},
    {label:"Buffalo Niagara International Airport",value:"BUF"},
    {label:"Charlotte/Douglas International Airport",value:"CLT"},
    {label:"Chicago Midway International Airport",value:"MDW"},
    {label:"Chicago O'Hare International Airport",value:"ORD"},
    {label:"Cincinnati Municipal Lunken Airport",value:"LUK"},
    {label:"Cleveland-Hopkins International Airport",value:"CLE"},
    {label:"City of Colorado Springs Municipal Airport",value:"COS"},
    {label:"John Glenn Columbus International Airport",value:"CMH"},
    {label:"Rickenbacker International Airport",value:"LCK"},
    {label:"Columbus Metropolitan Airport",value:"CSG"},
    {label:"Dallas Love Field",value:"DAL"},
    {label:"Denver International Airport",value:"DEN"},
    {label:"El Paso International Airport",value:"ELP"},
    {label:"Fort Wayne International Airport",value:"FWA"},
    {label:"Fresno Yosemite International Airport",value:"FAT"},
    {label:"Piedmont Triad International Airport",value:"GSO"},
    {label:"Daniel K. Inouye International Airport",value:"HNL"},
    {label:"George Bush Intercontinental Airport",value:"IAH"},
    {label:"William P. Hobby Airport",value:"HOU"},
    {label:"Indianapolis International Airport",value:"IND"},
    {label:"Albert J. Ellis Airport",value:"OAJ"},
    {label:"Jacksonville International Airport",value:"JAX"},
    {label:"Kansas City International Airport",value:"MCI"},
    {label:"Laredo International Airport",value:"LRD"},
    {label:"McCarran International Airport",value:"LAS"},
    {label:"Lincoln Airport",value:"LNK"},
    {label:"Long Beach Airport",value:"LGB"},
    {label:"Los Angeles International Airport",value:"LAX"},
    {label:"Louisville International Airport",value:"SDF"},
    {label:"Lubbock Preston Smith International Airport",value:"LBB"},
    {label:"Dane County Regional Airport",value:"MSN"},
    {label:"Memphis International Airport",value:"MEM"},
    {label:"Phoenix Mesa Gateway Airport",value:"IWA"},
    {label:"Miami International Airport",value:"MIA"},
    {label:"General Mitchell International Airport",value:"MKE"},
    {label:"Minneapolis?St. Paul International Airport",value:"MSP"},
    {label:"Nashville International Airport",value:"BNA"},
    {label:"Louis Armstrong New Orleans International Airport",value:"MSY"},
    {label:"LaGuardia Airport",value:"LGA"},
    {label:"John F. Kennedy International Airport",value:"JFK"},
    {label:"Newark Liberty International Airport",value:"EWR"},
    {label:"Norfolk International Airport",value:"ORF"},
    {label:"Oakland International Airport",value:"OAK"},
    {label:"Will Rogers World Airport",value:"OKC"},
    {label:"Eppley Airfield",value:"OMA"},
    {label:"Orlando International Airport",value:"MCO"},
    {label:"Philadelphia International Airport",value:"PHL"},
    {label:"Phoenix Sky Harbor International Airport",value:"PHX"},
    {label:"Pittsburgh International Airport",value:"PIT"},
    {label:"Portland International Airport",value:"PDX"},
    {label:"Portland International Jetport",value:"PWM"},
    {label:"Raleigh-Durham International Airport",value:"RDU"},
    {label:"Reno/Tahoe International Airport",value:"RNO"},
    {label:"Richmond International Airport",value:"RIC"},
    {label:"Sacramento International Airport",value:"SMF"},
    {label:"San Antonio International Airport",value:"SAT"},
    {label:"San Diego International Airport",value:"SAN"},
    {label:"San Francisco International Airport",value:"SFO"},
    {label:"Norman Y. Mineta San José International Airport",value:"SJC"},
    {label:"John Wayne Airport",value:"SNA"},
    {label:"King County International Airport",value:"BFI"},
    {label:"Spokane International Airport",value:"GEG"},
    {label:"St. Louis Lambert International Airport",value:"STL"},
    {label:"Stockton Metropolitan Airport",value:"SCK"},
    {label:"Tampa International Airport",value:"TPA"},
    {label:"Toledo Express Airport",value:"TOL"},
    {label:"Tucson International Airport",value:"TUS"},
    {label:"Tulsa International Airport",value:"TUL"},
    {label:"Wichita Dwight D. Eisenhower National Airport",value:"IC"}
];

export {AirportData};
