let AirportData = [
    {"value": "ABQ", "label": "Albuquerque International Sunport"},
    {"value": "ANC", "label": "Ted Stevens Anchorage International Airport"},
    {"value": "ATL", "label": "Hartsfield Jackson Atlanta International Airport"},
    {"value": "AUS", "label": "Austin-Bergstrom International Airport"},
    {"value": "BFL", "label": "Meadows Field"},
    {"value": "BNA", "label": "Nashville International Airport"},
    {"value": "BOI", "label": "Boise Airport"},
    {"value": "BOS", "label": "Gen. Edward Lawrence Logan International Airport"},
    {"value": "BTR", "label": "Baton Rouge Metropolitan Airport"},
    {"value": "BUF", "label": "Buffalo Niagara International Airport"},
    {"value": "BWI", "label": "Baltimore?Washington International Airport"},
    {"value": "CLE", "label": "Cleveland-Hopkins International Airport"},
    {"value": "CLT", "label": "Charlotte Douglas International Airport"},
    {"value": "CLT", "label": "Charlotte/Douglas International Airport"},
    {"value": "CMH", "label": "John Glenn Columbus International Airport"},
    {"value": "COS", "label": "City of Colorado Springs Municipal Airport"},
    {"value": "CRP", "label": "Corpus Christi International Airport"},
    {"value": "CSG", "label": "Columbus Metropolitan Airport"},
    {"value": "DAL", "label": "Dallas Love Field"},
    {"value": "DCA", "label": "Ronald Reagan Washington National Airport"},
    {"value": "DEN", "label": "Denver International Airport"},
    {"value": "DFW", "label": "Dallas Fort Worth International Airport"},
    {"value": "DTW", "label": "Detroit Metropolitan Wayne County Airport"},
    {"value": "ELP", "label": "El Paso International Airport"},
    {"value": "EWR", "label": "Newark Liberty International Airport"},
    {"value": "FAT", "label": "Fresno Yosemite International Airport"},
    {"value": "FWA", "label": "Fort Wayne International Airport"},
    {"value": "GEG", "label": "Spokane International Airport"},
    {"value": "GSO", "label": "Piedmont Triad International Airport"},
    {"value": "HNL", "label": "Daniel K. Inouye International Airport"},
    {"value": "HOU", "label": "William P. Hobby Airport"},
    {"value": "IAH", "label": "George Bush Intercontinental Airport"},
    {"value": "ICT", "label": "Wichita Dwight D. Eisenhower National Airport"},
    {"value": "IND", "label": "Indianapolis International Airport"},
    {"value": "JAX", "label": "Jacksonville International Airport"},
    {"value": "JFK", "label": "John F. Kennedy International Airport"},
    {"value": "LAS", "label": "North Las Vegas Airport"},
    {"value": "LAS", "label": "McCarran International Airport"},
    {"value": "LAX", "label": "Los Angeles International Airport"},
    {"value": "LBB", "label": "Lubbock Preston Smith International Airport"},
    {"value": "LCK", "label": "Rickenbacker International Airport"},
    {"value": "LEX", "label": "Blue Grass Airport"},
    {"value": "LGA", "label": "LaGuardia Airport"},
    {"value": "LGB", "label": "Long Beach Airport"},
    {"value": "LNK", "label": "Lincoln Airport"},
    {"value": "LRD", "label": "Laredo International Airport"},
    {"value": "MCI", "label": "Kansas City International Airport"},
    {"value": "MCO", "label": "Orlando International Airport"},
    {"value": "MDW", "label": "Chicago Midway International Airport"},
    {"value": "MEM", "label": "Memphis International Airport"},
    {"value": "MIA", "label": "Miami International Airport"},
    {"value": "MKE", "label": "General Mitchell International Airport"},
    {"value": "MSN", "label": "Dane County Regional Airport"},
    {"value": "MSP", "label": "Minneapolis St. Paul International Airport"},
    {"value": "MSY", "label": "Louis Armstrong New Orleans International Airport"},
    {"value": "OAJ", "label": "Albert J. Ellis Airport"},
    {"value": "OAK", "label": "Oakland International Airport"},
    {"value": "OKC", "label": "Will Rogers World Airport"},
    {"value": "OMA", "label": "Eppley Airfield"},
    {"value": "ORD", "label": "Chicago O'Hare International Airport"},
    {"value": "ORF", "label": "Norfolk International Airport"},
    {"value": "PDX", "label": "Portland International Airport"},
    {"value": "PHL", "label": "Philadelphia International Airport"},
    {"value": "PHX", "label": "Phoenix Sky Harbor International Airport"},
    {"value": "PIE", "label": "St Petersburg Clearwater International Airport"},
    {"value": "PIT", "label": "Pittsburgh International Airport"},
    {"value": "PWM", "label": "Portland International Jetport"},
    {"value": "RDU", "label": "Raleigh-Durham International Airport"},
    {"value": "RIC", "label": "Richmond International Airport"},
    {"value": "RNO", "label": "Reno/Tahoe International Airport"},
    {"value": "SAN", "label": "San Diego International Airport"},
    {"value": "SAT", "label": "San Antonio International Airport"},
    {"value": "SCK", "label": "Stockton Metropolitan Airport"},
    {"value": "SDF", "label": "Louisville International Airport"},
    {"value": "SFO", "label": "San Francisco International Airport"},
    {"value": "SJC", "label": "Norman Y. Mineta San José International Airport"},
    {"value": "SMF", "label": "Sacramento International Airport"},
    {"value": "SNA", "label": "John Wayne Airport"},
    {"value": "STL", "label": "St. Louis Lambert International Airport"},
    {"value": "TOL", "label": "Toledo Express Airport"},
    {"value": "TPA", "label": "Tampa International Airport"},
    {"value": "TUL", "label": "Tulsa International Airport"},
    {"value": "TUS", "label": "Tucson International Airport"}
    ];

export {AirportData};
